default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres


development:
  <<: *default
  database: sweetleadsbi_development


test:
  <<: *default
  database: sweetleadsbi_test
 

production:
  <<: *default
  database: sweetleadsbi_production
  username: seme
  password: <%= ENV['SWEETLEADSBI_DATABASE_PASSWORD'] %>